Raise an exception when the static size of an array field does not match the size of the provided list instead of silently writing incorrectly sized data.
fox-it/dissect.cstruct pull request #23
Opened 2023-01-28 19:58 UTC by skarnproject

Addresses issue #22.

2023-02-01 12:34 UTC, Schamper requested changes

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/exceptions.py
> +class ArraySizeMismatch(Error):
```suggestion
class ArraySizeError(Error):
```
I've been trying to think if there was some Python builtin error we could use but came up blank. I think it's better to rename this to be more consistent with other error names though.

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/types/base.py
> +from dissect.cstruct.exceptions import ArraySizeMismatch
```suggestion
from dissect.cstruct.exceptions import ArraySizeError
```

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/types/base.py
> +            ArraySizeMismatch: Raised when len(data) does not match the size of a statically sized array field.
```suggestion
            ArraySizeError: Raised when ``len(data)`` does not match the size of a statically sized array field.
```

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/types/base.py
> +            ArraySizeMismatch: Raised when len(data) does not match the size of a statically sized array field.
```suggestion
            ArraySizeError: Raised when ``len(data)`` does not match the size of a statically sized array field.
```

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/types/base.py
> +            raise ArraySizeMismatch(f"Expected static array size {self.count}, got {arr_size} instead.")
```suggestion
            raise ArraySizeError(f"Expected static array size {self.count}, got {actual_size} instead.")
```

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/types/base.py
> +        if not self.dynamic and self.count != (arr_size := len(data)):
```suggestion
        if not self.dynamic and self.count != (actual_size := len(data)):
```

2023-02-01 12:34 UTC, Schamper commented on dissect/cstruct/exceptions.py
> +
```suggestion
```
Make the linter happy.

2023-02-01 12:34 UTC, Schamper commented on tests/test_basic.py
> +
```suggestion
```
Make the linter happy.

2023-02-01 12:34 UTC, Schamper commented on tests/test_basic.py
> +    a = c.test(a=[1, 2, 3])
```suggestion
    cdef = """
    struct test {
        uint8   a[2];
    };
    """
    cs = cstruct.cstruct(endian=">")
    cs.load(cdef)

    a = cs.test(a=[1, 2, 3])
```

2023-02-03 01:04 UTC, Schamper commented
@skarnproject thanks, if you could give an ack on the CLA this is good to go!

2023-02-03 08:22 UTC, skarnproject commented
@DissectBot agree

2023-02-03 10:59 UTC, Schamper approved these changes

2023-02-03 11:01 UTC, merged