Add LEB128 variable-lengh integer support to cstruct v3
fox-it/dissect.cstruct pull request #73
Opened 2024-03-04 11:07 UTC by joost-j

Backport for https://github.com/fox-it/dissect.cstruct/pull/69. Basically copy-pasted the implementation from the v4 version, but slightly edited some implementation / test details to work with the cstruct v3 API.

2024-03-13 14:30 UTC, Schamper requested changes

2024-03-13 14:30 UTC, Schamper commented on dissect/cstruct/cstruct.py
> +            "ileb128": LEB128(self, 'ileb128', None, True, alignment=4),
Can the alignment be `None` or is that not supported in cstruct v3?

2024-03-13 14:30 UTC, Schamper commented on tests/test_types_leb128.py
> +    """
Can you incorporate a check to ensure that the compiler doesn't blow up?

2024-03-25 15:07 UTC, joost-j commented on dissect/cstruct/cstruct.py
> +            "ileb128": LEB128(self, 'ileb128', None, True, alignment=4),
Yes, it seems to work in combination with `size=0`, will push those changes

2024-03-25 15:13 UTC, joost-j commented on tests/test_types_leb128.py
> +    """
Added `compiled=compiled` to the tests

2024-03-25 15:29 UTC, Schamper requested changes

2024-03-25 15:29 UTC, Schamper commented on dissect/cstruct/types/leb128.py
> +from typing import TYPE_CHECKING, Any, BinaryIO, List
```suggestion
from typing import TYPE_CHECKING, Any, BinaryIO
```

2024-03-25 15:29 UTC, Schamper commented on dissect/cstruct/types/leb128.py
> +    def default_array(self, count: int) -> List[int]:
```suggestion
    def default_array(self, count: int) -> list[int]:
```

2024-03-25 15:29 UTC, Schamper commented on dissect/cstruct/types/leb128.py
> +    def _write_0(self, stream: BinaryIO, data: List[int]) -> int:
```suggestion
    def _write_0(self, stream: BinaryIO, data: list[int]) -> int:
```

2024-03-25 15:29 UTC, Schamper commented on dissect/cstruct/types/leb128.py
> +    See https://en.wikipedia.org/wiki/LEB128 for more information and an explanation of the algorithm.
```suggestion

    See https://en.wikipedia.org/wiki/LEB128 for more information and an explanation of the algorithm.
```

2024-03-25 15:29 UTC, Schamper commented on tests/test_types_leb128.py
> +def test_leb128_struct_unsigned(compiled):
```suggestion
@pytest.mark.parametrize("compiled", [True, False])
def test_leb128_struct_unsigned(compiled):
```
Can you add this everywhere? v3 doesn't have the fixture for this yet.

2024-03-26 11:46 UTC, Schamper requested changes

2024-03-26 11:46 UTC, Schamper commented on dissect/cstruct/cstruct.py
> +            "ileb128": LEB128(self, 'ileb128', None, True, alignment=1),
```suggestion
            "uleb128": LEB128(self, 'uleb128', None, False),
            "ileb128": LEB128(self, 'ileb128', None, True),
```

2024-03-26 11:46 UTC, Schamper commented on dissect/cstruct/types/leb128.py
> +    def __init__(self, cstruct: cstruct, name: str, size: int, signed: bool, alignment: int = None):
```suggestion
    def __init__(self, cstruct: cstruct, name: str, size: int, signed: bool, alignment: int = 1):
```

2024-03-26 13:07 UTC, Schamper approved these changes

2024-03-27 10:23 UTC, merged