Add examples and unit tests for custom types in cstruct v4
fox-it/dissect.cstruct pull request #83
Opened 2024-04-22 13:00 UTC by Miauwkeru

2024-05-13 14:06 UTC, Schamper requested changes

2024-05-13 14:06 UTC, Schamper commented on examples/protobuf.py
> +    def _read(cls, stream: BinaryIO, context: dict[str, Any] = None) -> int:
```suggestion
    def _read(cls, stream: BinaryIO, context: dict[str, Any] | None = None) -> int:
```

2024-05-14 15:33 UTC, cecinestpasunepipe approved these changes

2024-05-14 16:03 UTC, Schamper approved these changes

2024-05-15 07:49 UTC, merged