fix offsets in generate fields
fox-it/dissect.cstruct pull request #93
Opened 2024-06-03 12:13 UTC by Miauwkeru

- Unpack enum when generating fields.
- Align bit fields better

2024-06-03 16:19 UTC, Miauwkeru commented on dissect/cstruct/compiler.py
>                      bits_rollover = True
Note:
This will still leave space in a structure. 
so with the following example:
```python
struct data {
  uint64 a: 4,
  uint16 b: 4,
};

data(a=4, b=5).dumps() == b"\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00"
```
this is done for both reading and writing, which might result in unwanted stuff

2024-06-04 08:49 UTC, pyrco requested changes

2024-06-04 08:49 UTC, pyrco commented on tests/test_compiler.py
> +# TODO: the rest of the compiler
```suggestion
```

2024-06-04 08:49 UTC, pyrco commented on tests/test_compiler.py
>  # TODO: the rest of the compiler
```suggestion
```

2024-06-04 08:49 UTC, pyrco commented on tests/test_compiler.py
> +def test_generate_fields_dynamic_after_bitfield_reverse(cs: cstruct, TestEnum: Enum, other_type: str) -> None:
```suggestion
def test_generate_fields_dynamic_before_bitfield(cs: cstruct, TestEnum: Enum, other_type: str) -> None:
```

2024-06-04 09:15 UTC, pyrco approved these changes

2024-06-04 09:34 UTC, merged